// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/contracted-transport" | "/contracted-transport/[id]" | "/contracted-transport/[id]/edit" | "/contracted-transport/new" | "/contracts" | "/contracts/[id]" | "/contracts/new" | "/contracts/templates/[id]" | "/contracts/templates/new" | "/customers" | "/customers/[id]" | "/customers/[id]/edit" | "/customers/[id]/employees/[employeeId]/edit" | "/customers/[id]/employees/new" | "/customers/new" | "/dashboard" | "/direct-shipments" | "/drivers" | "/drivers/[id]" | "/drivers/[id]/edit" | "/drivers/new" | "/drivers/reconciliation" | "/fuel" | "/fuel/[id]/edit" | "/fuel/new" | "/login" | "/maintenances" | "/maintenances/[id]/edit" | "/maintenances/new" | "/management" | "/management/managers/[id]" | "/monitoring" | "/my-dashboard" | "/optimize-route" | "/profile" | "/quotes" | "/quotes/[id]" | "/quotes/[id]/edit" | "/quotes/[id]/items/[itemId]/edit" | "/quotes/new" | "/reports" | "/safety-briefing/[id]" | "/safety-briefings/[id]" | "/settings" | "/settings/industries" | "/settings/packaging-types" | "/settings/regions" | "/settings/service-types" | "/settings/trailer-types" | "/settings/vehicle-definitions" | "/settings/vehicle-makes" | "/settings/vehicle-models" | "/settings/vehicle-types" | "/shipments" | "/shipments/[id]" | "/shipments/[id]/report" | "/shipments/new" | "/sign/[id]" | "/signup" | "/transport-operations" | "/transport-operations/dispatch" | "/transport-operations/end-to-end" | "/transport-operations/end-to-end/[id]" | "/transport-operations/schedule" | "/transport-operations/tracking" | "/transport-operations/trips" | "/users" | "/vehicles" | "/vehicles/[id]" | "/vehicles/[id]/edit" | "/vehicles/new" | "/warehouses" | "/warehouses/[id]" | "/warehouses/[id]/edit" | "/warehouses/new"
type AppRouteHandlerRoutes = "/api/contracted-transport/send-to-sheet" | "/api/quotes/excel" | "/api/quotes/pdf" | "/api/quotes/send-to-sheet"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/contracted-transport/send-to-sheet": {}
  "/api/quotes/excel": {}
  "/api/quotes/pdf": {}
  "/api/quotes/send-to-sheet": {}
  "/contracted-transport": {}
  "/contracted-transport/[id]": { "id": string; }
  "/contracted-transport/[id]/edit": { "id": string; }
  "/contracted-transport/new": {}
  "/contracts": {}
  "/contracts/[id]": { "id": string; }
  "/contracts/new": {}
  "/contracts/templates/[id]": { "id": string; }
  "/contracts/templates/new": {}
  "/customers": {}
  "/customers/[id]": { "id": string; }
  "/customers/[id]/edit": { "id": string; }
  "/customers/[id]/employees/[employeeId]/edit": { "id": string; "employeeId": string; }
  "/customers/[id]/employees/new": { "id": string; }
  "/customers/new": {}
  "/dashboard": {}
  "/direct-shipments": {}
  "/drivers": {}
  "/drivers/[id]": { "id": string; }
  "/drivers/[id]/edit": { "id": string; }
  "/drivers/new": {}
  "/drivers/reconciliation": {}
  "/fuel": {}
  "/fuel/[id]/edit": { "id": string; }
  "/fuel/new": {}
  "/login": {}
  "/maintenances": {}
  "/maintenances/[id]/edit": { "id": string; }
  "/maintenances/new": {}
  "/management": {}
  "/management/managers/[id]": { "id": string; }
  "/monitoring": {}
  "/my-dashboard": {}
  "/optimize-route": {}
  "/profile": {}
  "/quotes": {}
  "/quotes/[id]": { "id": string; }
  "/quotes/[id]/edit": { "id": string; }
  "/quotes/[id]/items/[itemId]/edit": { "id": string; "itemId": string; }
  "/quotes/new": {}
  "/reports": {}
  "/safety-briefing/[id]": { "id": string; }
  "/safety-briefings/[id]": { "id": string; }
  "/settings": {}
  "/settings/industries": {}
  "/settings/packaging-types": {}
  "/settings/regions": {}
  "/settings/service-types": {}
  "/settings/trailer-types": {}
  "/settings/vehicle-definitions": {}
  "/settings/vehicle-makes": {}
  "/settings/vehicle-models": {}
  "/settings/vehicle-types": {}
  "/shipments": {}
  "/shipments/[id]": { "id": string; }
  "/shipments/[id]/report": { "id": string; }
  "/shipments/new": {}
  "/sign/[id]": { "id": string; }
  "/signup": {}
  "/transport-operations": {}
  "/transport-operations/dispatch": {}
  "/transport-operations/end-to-end": {}
  "/transport-operations/end-to-end/[id]": { "id": string; }
  "/transport-operations/schedule": {}
  "/transport-operations/tracking": {}
  "/transport-operations/trips": {}
  "/users": {}
  "/vehicles": {}
  "/vehicles/[id]": { "id": string; }
  "/vehicles/[id]/edit": { "id": string; }
  "/vehicles/new": {}
  "/warehouses": {}
  "/warehouses/[id]": { "id": string; }
  "/warehouses/[id]/edit": { "id": string; }
  "/warehouses/new": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
