// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/contracted-transport/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contracted-transport/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/contracted-transport/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/contracted-transport/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contracted-transport/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/contracted-transport/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/contracted-transport/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contracted-transport/new">> = Specific
  const handler = {} as typeof import("../../src/app/contracted-transport/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/contracted-transport/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contracted-transport">> = Specific
  const handler = {} as typeof import("../../src/app/contracted-transport/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/contracts/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contracts/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/contracts/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/contracts/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contracts/new">> = Specific
  const handler = {} as typeof import("../../src/app/contracts/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/contracts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contracts">> = Specific
  const handler = {} as typeof import("../../src/app/contracts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/contracts/templates/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contracts/templates/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/contracts/templates/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/contracts/templates/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contracts/templates/new">> = Specific
  const handler = {} as typeof import("../../src/app/contracts/templates/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customers/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customers/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/customers/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customers/[id]/employees/[employeeId]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customers/[id]/employees/[employeeId]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/customers/[id]/employees/[employeeId]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customers/[id]/employees/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customers/[id]/employees/new">> = Specific
  const handler = {} as typeof import("../../src/app/customers/[id]/employees/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customers/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customers/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/customers/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customers/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customers/new">> = Specific
  const handler = {} as typeof import("../../src/app/customers/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customers">> = Specific
  const handler = {} as typeof import("../../src/app/customers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/direct-shipments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/direct-shipments">> = Specific
  const handler = {} as typeof import("../../src/app/direct-shipments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/drivers/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/drivers/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/drivers/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/drivers/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/drivers/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/drivers/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/drivers/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/drivers/new">> = Specific
  const handler = {} as typeof import("../../src/app/drivers/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/drivers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/drivers">> = Specific
  const handler = {} as typeof import("../../src/app/drivers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/drivers/reconciliation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/drivers/reconciliation">> = Specific
  const handler = {} as typeof import("../../src/app/drivers/reconciliation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/fuel/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fuel/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/fuel/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/fuel/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fuel/new">> = Specific
  const handler = {} as typeof import("../../src/app/fuel/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/fuel/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fuel">> = Specific
  const handler = {} as typeof import("../../src/app/fuel/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/maintenances/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenances/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/maintenances/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/maintenances/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenances/new">> = Specific
  const handler = {} as typeof import("../../src/app/maintenances/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/maintenances/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenances">> = Specific
  const handler = {} as typeof import("../../src/app/maintenances/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/management/managers/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/management/managers/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/management/managers/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/management/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/management">> = Specific
  const handler = {} as typeof import("../../src/app/management/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/monitoring/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/monitoring">> = Specific
  const handler = {} as typeof import("../../src/app/monitoring/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/my-dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/my-dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/my-dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/optimize-route/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/optimize-route">> = Specific
  const handler = {} as typeof import("../../src/app/optimize-route/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../src/app/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/quotes/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/quotes/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/quotes/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/quotes/[id]/items/[itemId]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/quotes/[id]/items/[itemId]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/quotes/[id]/items/[itemId]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/quotes/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/quotes/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/quotes/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/quotes/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/quotes/new">> = Specific
  const handler = {} as typeof import("../../src/app/quotes/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/quotes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/quotes">> = Specific
  const handler = {} as typeof import("../../src/app/quotes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports">> = Specific
  const handler = {} as typeof import("../../src/app/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/safety-briefing/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/safety-briefing/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/safety-briefing/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/safety-briefings/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/safety-briefings/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/safety-briefings/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/settings/industries/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/industries">> = Specific
  const handler = {} as typeof import("../../src/app/settings/industries/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/settings/packaging-types/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/packaging-types">> = Specific
  const handler = {} as typeof import("../../src/app/settings/packaging-types/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../src/app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/settings/regions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/regions">> = Specific
  const handler = {} as typeof import("../../src/app/settings/regions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/settings/service-types/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/service-types">> = Specific
  const handler = {} as typeof import("../../src/app/settings/service-types/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/settings/trailer-types/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/trailer-types">> = Specific
  const handler = {} as typeof import("../../src/app/settings/trailer-types/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/settings/vehicle-definitions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/vehicle-definitions">> = Specific
  const handler = {} as typeof import("../../src/app/settings/vehicle-definitions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/settings/vehicle-makes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/vehicle-makes">> = Specific
  const handler = {} as typeof import("../../src/app/settings/vehicle-makes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/settings/vehicle-models/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/vehicle-models">> = Specific
  const handler = {} as typeof import("../../src/app/settings/vehicle-models/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/settings/vehicle-types/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/vehicle-types">> = Specific
  const handler = {} as typeof import("../../src/app/settings/vehicle-types/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/shipments/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shipments/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/shipments/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/shipments/[id]/report/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shipments/[id]/report">> = Specific
  const handler = {} as typeof import("../../src/app/shipments/[id]/report/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/shipments/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shipments/new">> = Specific
  const handler = {} as typeof import("../../src/app/shipments/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/shipments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shipments">> = Specific
  const handler = {} as typeof import("../../src/app/shipments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/sign/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sign/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/sign/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../src/app/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/transport-operations/dispatch/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/transport-operations/dispatch">> = Specific
  const handler = {} as typeof import("../../src/app/transport-operations/dispatch/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/transport-operations/end-to-end/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/transport-operations/end-to-end/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/transport-operations/end-to-end/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/transport-operations/end-to-end/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/transport-operations/end-to-end">> = Specific
  const handler = {} as typeof import("../../src/app/transport-operations/end-to-end/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/transport-operations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/transport-operations">> = Specific
  const handler = {} as typeof import("../../src/app/transport-operations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/transport-operations/schedule/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/transport-operations/schedule">> = Specific
  const handler = {} as typeof import("../../src/app/transport-operations/schedule/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/transport-operations/tracking/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/transport-operations/tracking">> = Specific
  const handler = {} as typeof import("../../src/app/transport-operations/tracking/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/transport-operations/trips/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/transport-operations/trips">> = Specific
  const handler = {} as typeof import("../../src/app/transport-operations/trips/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/users">> = Specific
  const handler = {} as typeof import("../../src/app/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/vehicles/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vehicles/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/vehicles/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/vehicles/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vehicles/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/vehicles/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/vehicles/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vehicles/new">> = Specific
  const handler = {} as typeof import("../../src/app/vehicles/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/vehicles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vehicles">> = Specific
  const handler = {} as typeof import("../../src/app/vehicles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/warehouses/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/warehouses/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/warehouses/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/warehouses/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/warehouses/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/warehouses/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/warehouses/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/warehouses/new">> = Specific
  const handler = {} as typeof import("../../src/app/warehouses/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/warehouses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/warehouses">> = Specific
  const handler = {} as typeof import("../../src/app/warehouses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/contracted-transport/send-to-sheet/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contracted-transport/send-to-sheet">> = Specific
  const handler = {} as typeof import("../../src/app/api/contracted-transport/send-to-sheet/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/quotes/excel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quotes/excel">> = Specific
  const handler = {} as typeof import("../../src/app/api/quotes/excel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/quotes/pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quotes/pdf">> = Specific
  const handler = {} as typeof import("../../src/app/api/quotes/pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/quotes/send-to-sheet/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quotes/send-to-sheet">> = Specific
  const handler = {} as typeof import("../../src/app/api/quotes/send-to-sheet/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
